apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-flask
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-flask
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      nodePort: 30007  # Optional: Specify or let K8s assign
